CREATE DATABASE TFG;
USE TFG;
CREATE TABLE USERS(
    id PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,

);

CREATE TABLE CARDS(
    id PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255),
    precio DECIMAL(7,2),
)

CREATE TABLE COLLECTION (
    id PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
)